Description: YAML Configuration file for unit test in BASE
ProductNames:
- teams
- exo
- defender
- aad
- sharepoint
- onedrive
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
AnObject:
  name: MyObjectName
